In [2]:
import numpy as np

A=np.array([[2,1,0],[1,2,1],[0,1,2]])
print(A)

[[2 1 0]
 [1 2 1]
 [0 1 2]]


In [3]:
A[[0,1]]=A[[1,0]]
print(A)

[[1 2 1]
 [2 1 0]
 [0 1 2]]


In [4]:
A[1]=-2*A[0] + A[1]
print(A)

[[ 1  2  1]
 [ 0 -3 -2]
 [ 0  1  2]]


In [5]:
A[[1,2]]=A[[2,1]]
print(A)

[[ 1  2  1]
 [ 0  1  2]
 [ 0 -3 -2]]


In [6]:
A[2]=3*A[1]+A[2]
print(A)

[[1 2 1]
 [0 1 2]
 [0 0 4]]


In [9]:
DetA=1*1*4
print("Determinan A:", DetA)

Determinan A: 4


In [10]:
diagA=np.diag(A)
print(diagA)

[1 1 4]


In [12]:
detA=np.prod(diagA)
print(detA)

4


In [13]:
detA=np.prod(np.diag(A))
print(detA)

4


In [15]:
print(A)
diag1=A.diagonal(0)
diag2=A.diagonal(1)

print("diagonal 1:",diag1)
print("diagonal 2:",diag2)

[[1 2 1]
 [0 1 2]
 [0 0 4]]
diagonal 1: [1 1 4]
diagonal 2: [2 2]


In [16]:
B=np.array([[3,2,-1],[1,1,0],[-2,-2,1]])
print(B)

[[ 3  2 -1]
 [ 1  1  0]
 [-2 -2  1]]


In [17]:
B1=np.hstack([B,B[:,:2]])
print(B1)

[[ 3  2 -1  3  2]
 [ 1  1  0  1  1]
 [-2 -2  1 -2 -2]]


In [19]:
#diagonal miring kiri
d1=B1.diagonal(0)
d2=B1.diagonal(1)
d3=B1.diagonal(2)
#diagonal miring kanan
d4=np.fliplr(B1).diagonal(0)
d5=np.fliplr(B1).diagonal(1)
d6=np.fliplr(B1).diagonal(2)

print(B1)
print(d1,d2,d3,d4,d5,d6)

[[ 3  2 -1  3  2]
 [ 1  1  0  1  1]
 [-2 -2  1 -2 -2]]
[3 1 1] [ 2  0 -2] [-1  1 -2] [2 1 1] [ 3  0 -2] [-1  1 -2]


In [20]:
detB=np.prod(d1) + np.prod(d2) + np.prod(d3) - np.prod(d4) - np.prod(d5) - np.prod(d6)
print(detB)

1


In [24]:
print(A)
M31=np.delete(np.delete (A,2,axis=0), 0, axis=1)
print(M31)

m31=np.prod(np.diag(M31))-np.prod(np.diag(np.fliplr(M31)))
print("miror 31=", m31)

[[1 2 1]
 [0 1 2]
 [0 0 4]]
[[2 1]
 [1 2]]
miror 31= 3


In [23]:
C31=((-1)**(3+1))*m31
print(C31)

3


In [25]:
M32=np.delete(np.delete (A,2,axis=0), 1, axis=1)
print(M32)

m32=np.prod(np.diag(M32))-np.prod(np.diag(np.fliplr(M32)))
print("miror 32=", m32)

M33=np.delete(np.delete (A,2,axis=0), 2, axis=1)
print(M33)

m33=np.prod(np.diag(M33))-np.prod(np.diag(np.fliplr(M33)))
print("miror 33=", m33)

[[1 1]
 [0 2]]
miror 32= 2
[[1 2]
 [0 1]]
miror 33= 1


In [27]:
C32=((-1)**(3+2))*m32
print(C32)
C33=((-1)**(3+3))*m33
print(C33)

-2
1
